export { default as Switch } from './Switch/Switch'
export { default as SideMenu } from './SideMenu/SideMenu'
export { default as SideMenuItem } from './SideMenu/Item/SideMenuItem'
export { default as Button } from './Button/Button'
export { default as Title } from './Title/Title'
export { default as Heading } from './Heading/Heading'
export { default as Heading2 } from './Heading2/Heading2'
export { default as Heading3 } from './Heading3/Heading3'